---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-demo-deployment-v2
spec:
  scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: hpa-demo-deployment-v2
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hpa-demo-deployment-v2
spec:
 selector:
   matchLabels:
     run: hpa-demo-deployment-v2
 replicas: 1
 template:
   metadata:
     labels:
       run: hpa-demo-deployment-v2
   spec:
     containers:
     - name: hpa-demo-deployment-v2
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
 name: hpa-demo-deployment-v2
 labels:
   run: hpa-demo-deployment-v2
spec:
 ports:
 - port: 80
 selector:
   run: hpa-demo-deployment-v2
